// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBla2Z88pN-pe_nzlSp9j-5MqDAU7YXMoM',
    appId: '1:530272225775:web:6eb385670df11220134e1a',
    messagingSenderId: '530272225775',
    projectId: 'proyectofinal-cd19f',
    authDomain: 'proyectofinal-cd19f.firebaseapp.com',
    storageBucket: 'proyectofinal-cd19f.firebasestorage.app',
    measurementId: 'G-5ERDKF3G9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9TgW88VXQcHR_b4dhanGzuvs12xFNqV4',
    appId: '1:530272225775:android:b209e04ba023b0b4134e1a',
    messagingSenderId: '530272225775',
    projectId: 'proyectofinal-cd19f',
    storageBucket: 'proyectofinal-cd19f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbht1Zg3EdHKQegxxljHEA56Y3Cdflefw',
    appId: '1:530272225775:ios:40529fe3f4b193a2134e1a',
    messagingSenderId: '530272225775',
    projectId: 'proyectofinal-cd19f',
    storageBucket: 'proyectofinal-cd19f.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbht1Zg3EdHKQegxxljHEA56Y3Cdflefw',
    appId: '1:530272225775:ios:40529fe3f4b193a2134e1a',
    messagingSenderId: '530272225775',
    projectId: 'proyectofinal-cd19f',
    storageBucket: 'proyectofinal-cd19f.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBla2Z88pN-pe_nzlSp9j-5MqDAU7YXMoM',
    appId: '1:530272225775:web:6eb385670df11220134e1a',
    messagingSenderId: '530272225775',
    projectId: 'proyectofinal-cd19f',
    authDomain: 'proyectofinal-cd19f.firebaseapp.com',
    storageBucket: 'proyectofinal-cd19f.firebasestorage.app',
    measurementId: 'G-5ERDKF3G9G',
  );

}